export const ROOT_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const BUILDER_ROUTE = '/build'
export const DASHBOARD_ROUTE = '/dashboard'
export const VIEWER_ROUTE = '/p/:slug'

export const ISSUE_MEMO_LANDING_ROUTE = '/issue/:templateId'
export const ISSUE_MEMO_SAMPLE_CSV_ROUTE = 'issue/:templateId/bulk/download'
export const ISSUE_MEMO_BULK_ROUTE = 'issue/:templateId/bulk'
export const ISSUE_MEMO_SINGLE_ROUTE = '/issue/:templateId/single'
export const ISSUE_MEMO_SINGLE_SUCCESS_ROUTE = '/issue/single/success'
